"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

includes = []
with open("requirements_mac.txt") as f:
    for x in f:
        includes.append(x.strip("\n").split("==")[0])

APP = ['main.py']
DATA_FILES = []
OPTIONS = {
    'includes': includes,
    'iconfile': "src/resource/appico.icns",
    'resources': [],
    'plist': {
        'CFBundleName': 'EasyPic',  # 应用名
        'CFBundleDisplayName': 'EasyPic',  # 应用显示名
        'CFBundleVersion': '0.0.1.dev',  # 应用版本号
        'CFBundleIdentifier': 'daigua.app.easypic',  # 应用包名、唯一标识
        'NSHumanReadableCopyright': 'Copyright © 2021 SW Felix.Zhao. All rights reserved.',  # 可读版权
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
